### PR TITLE
GetUserId by organization name and user name

### PR DESCRIPTION
**Pull request by tapaszto**
This is a feature upgrade utilizing the user entitlements DevOps API 
The GeUserID function of the UserEntitlementsService returns the Azure DevOps user id by the organization name and user name, this functionality is required to be able to fix an Azure related bug of runatlantis/atlantis
New files:
 userentitlements.go: contains the new functionality
 examples/getuserid/main.go: an example of using the new functionality
Modified files:
 azuredevops.go: UserEntitlementService is added

### CODE REVIEW

**Comment by Dilergore** [comment]
Hey @mcdafydd,

We are planning to fix the merge issue bug in Atlantis which for we need this as a prereq. Could you please review this so we can continue the work on the Atlantis side?

https://github.com/runatlantis/atlantis/issues/1152

**Comment by mcdafydd** [comment]
Thanks for this.  I will get to it later today.

**Comment by mcdafydd** [comment]
Hello,

I think we can remove the NewRequestEx() approach.  We do something similar with a custom baseURL here:

https://github.com/mcdafydd/go-azuredevops/blob/aa2ceb158791b72bde63866088bb07af51b590c3/azuredevops/users.go#L148-L150

Also, would you add a simple test for each func and add omitempty to any receiving (response) JSON struct members?

Appreciate the submission!

**Comment by tapaszto** [comment]
Hi,

 I will make it on Monday, thanks.

**Comment by tapaszto** [comment]
Hi @mcdafydd,

I made the requested changes, can You please review it, and approve the PR?

**Comment by tapaszto** [comment]
Hi @mcdafydd,

Thanks for merging the PR, can You roll out a new release?

**Comment by mcdafydd** [comment]
Oh yes - sorry about that.

**Comment by mcdafydd** [comment]
Pushed tag `v0.12.0`

**Pull request merged**
